name: uno_vision
description: "UNO Vision – AI-powered UNO score tracker"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Network
  dio: ^5.4.0
  web_socket_channel: ^3.0.1

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Local Storage
  shared_preferences: ^2.3.2

  # ML / Camera
  tflite_flutter: ^0.11.0
  camera: ^0.11.0
  image: ^4.1.0
  image_picker: ^1.1.2 # For Debugging

  # UI
  google_fonts: ^6.2.1
  confetti: ^0.7.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0

  # Utils
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true  # Für Lokalisierung

  assets:
    - assets/models/